services:
  backend:
    image: freecontainer.azurecr.io/backend:latest

    environment:
      - DJANGO_SETTINGS_MODULE=freelancenowbackend.settings
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URI=${REDIS_URI}

    ports:
      - 29000:8000
  frontend:
    image: freecontainer.azurecr.io/frontend:latest
    command: npm run dev  
    ports:
      - "29002:5173"
      - "29003:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=prod
    stdin_open: true

