services:
  backend:
    image: freecontainer.azurecr.io/backend:latest
    environment:
      - DJANGO_SETTINGS_MODULE=freelancenowbackend.settings
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URI=${REDIS_URI}
    ports:
      - 29000:8000
    networks:
      - app-network

  frontend:
    image: freecontainer.azurecr.io/frontend:latest
    command: npm run dev  
    ports:
      - "29002:5173"
      - "29003:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=prod
    stdin_open: true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Exponemos el puerto 80 para el tráfico HTTP
    depends_on:
      - frontend
      - backend
    volumes:
      - ${WEBAPP_STORAGE_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf  # Monta la configuración desde el almacenamiento de Azure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
