# Base image Python 3.11 (For Django 5.1.1)
FROM python:3.10

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1  
ENV PYTHONUNBUFFERED=1          

RUN apt-get update && \
    apt-get install -y gcc libpq-dev netcat-openbsd curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/* &&\
    python -m venv /py && \
    /py/bin/pip install --upgrade pip 

COPY requirements.txt /tmp/requirements.txt
COPY requirements.dev.txt /tmp/requirements.dev.txt

RUN /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    /py/bin/pip install -r /tmp/requirements.dev.txt && \
    rm -rf /tmp 

COPY ./freelancenowbackend /app/

ENV PATH="/py/bin:$PATH"


