# Generated by Django 5.1.1 on 2024-10-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_status_alter_project_status_delete_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
    ]
