# Generated by Django 5.1.1 on 2024-10-01 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_project_area_remove_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancerskill', to='app.skill'),
        ),
    ]
