# Generated by Django 5.1.1 on 2024-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_milestone_file_project_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
