# Generated by Django 5.1.1 on 2024-10-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_freelancer_id_alter_freelancer_user'),
        ('app', '0003_milestone_status'),
    ]

    operations = [
    ]
