# Generated by Django 5.1.1 on 2024-10-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
