# Generated by Django 5.1.1 on 2024-09-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skilltype_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
