# Generated by Django 5.1.1 on 2024-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20241013_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
