# Generated by Django 5.1.1 on 2024-10-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20241013_1348'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='area',
            name='unique_area_name_per_company',
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('name', 'company', 'user'), name='unique_area_name_per_company'),
        ),
    ]
