# Generated by Django 5.1.1 on 2024-10-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_area_unique_area_name_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='area',
            name='unique_area_name_per_company',
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_area_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_area_per_user'),
        ),
    ]
