# Generated by Django 5.1.1 on 2024-10-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_project_profile_picture_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
