# Generated by Django 5.1.1 on 2024-09-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_deliverable_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('in course', 'In course')], default='pending'),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
