# Generated by Django 5.1.1 on 2024-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_project_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
