# Generated by Django 5.1.1 on 2024-09-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
