---
name: Checks

on: [push]


jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Clona el repositorio

      - name: Build Docker image
        run: docker compose build  # Construye la imagen de Docker basada en el código actual

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"



        